### PR TITLE
PE-23297-setup-ssh-access-between-task-runner-and-nodes

### PR DESCRIPTION
**Pull request by shaigy**
Add a method to setup ssh access between taskrunner and other nodes
for running bolt task

### CODE REVIEW

**Comment by shaigy** [comment]
setup/install.rb passed in 603.36 seconds
      Test Suite: pre_suite @ 2018-06-04 16:56:05 -0700

      - Host Configuration Summary -


              - Test Case Summary for suite 'pre_suite' -
       Total Suite Time: 603.33 seconds
      Average Test Time: 603.33 seconds
              Attempted: 1
                 Passed: 1
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 1

**Comment by cthorn42** [comment]
👍

**Comment by shaigy** [comment]
Sorry, I need to update this Pr with a small change. Will be done shortly

**Comment by shaigy** [comment]
Done!

**Pull request merged**
